#! /bin/sh
bspc rule -r "*"

# keybindings
killall sxhkd
sxhkd &

# X config
xrdb ~/.Xresources &

# compositor (transparancy n' stuff)
killall compton
compton --config ~/.config/compton/compton.conf &

# wallpaper
killall feh
feh --bg-scale ~/Pictures/ecopetit.cat-city-wallpaper-20102.png &

# monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# window border & gap
bspc config border_width        0
# bspc config top_padding         32
bspc config window_gap          32
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# window rules
bspc rule -a URxvt:floatterm state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# window colors
# bspc config normal_border_color	"4c566a"
# bspc config active_border_color	"#1e1e1e"
# bspc config focused_border_color "#406ea5"
# bspc config presel_feedback_color	"#5e81ac"
# bspc config urgent_border_color "#dd2727"