#! /bin/sh
bspc rule -r "*"

# keybindings
killall sxhkd
sxhkd &

# X config
xrdb ~/.Xresources &

# compositor (transparancy n' stuff)
killall compton
compton --config ~/.config/compton/compton.conf &

# wallpaper
killall feh
feh --bg-scale ~/Pictures/ecopetit.cat-city-wallpaper-20102.png &

# bar
killall polybar
polybar --config=/home/martin/.config/polybar/config example &

# monitor
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9

# window border & gap
bspc config border_width        0
# bspc config top_padding         32
bspc config window_gap          32
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# window rules
bspc rule -a URxvt:scratchtty state=floating sticky=on
# bspc rule -a Code desktop='^2'
# bspc rule -a Firefox desktop='^3'
bspc rule -a Inkscape desktop='^7' rectangle=1600x1200+0+0 state=floating follow=on focus=on center=on
bspc rule -a Gimp desktop='^8' rectangle=1600x1200+0+0 state=floating follow=on focus=on center=on

# -- work layouts

# load state
bspc wm -l ~/.config/bspwm/states/state.json

# defined rules
bspc rule -a URxvt:devtty1 -o node=@^1:^2:/1/1
bspc rule -a URxvt:devtty2 -o node=@^1:^2:/1/2
bspc rule -a Code:code -o node=@^1:^2:/2/1
bspc rule -a Firefox:Navigator -o node=@^1:^2:/2/2
